/*
    Schema Model Object
    -------------------------------
    This script was generated by SQL Change Automation to help provide object-level history in conjunction with your
    version control system.
    It is also useful for highlighting conflicts when merging in new migration scripts from version control.

    This script should never be edited manually.
    If you do have a version control conflict, it is advised that you fix the issue in your migration scripts,
    and then regenerate this script.
    For more information please refer to the documentation: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[DemoUpdateBaseline]
(
[SimpleColumn] [int] NULL
)
GO
